Correct an argument of PyArg_ParseTupleAndKeywords to fix a runtime error.
Former code passed a malformed value "s#|i|B" to PyArg_ParseTupleAndKeyword.
In recent Python versions, this could cause runtime errors such as
RuntimeError: Invalid format string (| specified twice).
This commit will fix such a problem.